[buildPlans.IosevkaFelix]
family = "Iosevka Felix"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaFelix.variants]
  inherits = "ss20"

    [buildPlans.IosevkaFelix.variants.design]
    capital-a = "curly-serifless"
    capital-b = "more-asymmetric-interrupted-serifless"
    capital-c = "serifless"
    capital-d = "more-rounded-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-j = "serifless"
    capital-l = "serifless"
    capital-m = "slanted-sides-hanging-serifless"
    capital-n = "asymmetric-serifless"
    capital-p = "open-serifless"
    capital-q = "open-swash"
    capital-r = "curly-open-serifless"
    a = "double-storey-toothless-rounded"
    b = "toothless-rounded-serifless"
    d = "toothless-rounded-serifless"
    e = "rounded"
    f = "flat-hook-tailed"
    g = "single-storey-flat-hook-earless-rounded"
    i = "tailed-serifed"
    j = "serifless"
    k = "curly-serifless"
    l = "tailed-serifed"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "earless-rounded-straight-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-straight-serifless"
    r = "earless-rounded-serifless"
    t = "bent-hook-asymmetric"
    u = "toothless-rounded-serifless"
    v = "curly-serifless"
    w = "curly-serifless"
    y = "cursive-serifless"
    zero = "dotted"
    one = "no-base"
    three = "flat-top-serifless"
    four = "open-non-crossing-serifless"
    five = "upright-flat-serifless"
    six = "open-contour"
    seven = "bend-serifless"
    eight = "crossing-asymmetric"
    asterisk = "hex-mid"
    underscore = "high"
    paren = "large-contour"
    brace = "curly-flat-boundary"
    ampersand = "upper-open"
    at = "compact"
    dollar = "interrupted"
    cent = "open"
    bar = "natural-slope"
    question = "smooth"
    pilcrow = "high"
    lig-ltgteq = "slanted"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"

  [buildPlans.IosevkaFelix.ligations]
  inherits = "dlig"