[buildPlans.IosevkaFelix]
family = "Iosevka Felix"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

	[buildPlans.IosevkaFelix.variants]
	inherits = "ss20"

		[buildPlans.IosevkaFelix.variants.design]
		one = "base"
		two = "curly-neck-serifless"
		three = "flat-top-serifless"
		four = "open-non-crossing-serifless"
		five = "upright-flat-serifless"
		six = "open-contour"
		seven = "bend-serifless"
		eight = "crossing-asymmetric"
		zero = "dotted"
		capital-a = "round-top-serifless"
		capital-b = "more-asymmetric-interrupted-serifless"
		capital-c = "serifless"
		capital-d = "more-rounded-serifless"
		capital-g = "toothless-corner-serifless-hooked"
		capital-j = "flat-hook-serifed"
		capital-l = "serifless"
		capital-m = "slanted-sides-hanging-serifless"
		capital-n = "asymmetric-serifless"
		capital-p = "open-serifless"
		capital-q = "open-swash"
		capital-r = "curly-open-serifless"
		a = "double-storey-toothless-rounded"
		b = "toothless-rounded-serifless"
		d = "toothless-rounded-serifless"
		e = "rounded"
		f = "flat-hook-tailed"
		g = "single-storey-flat-hook-earless-rounded"
		i = "serifed-flat-tailed"
		j = "serifed"
		k = "curly-serifless"
		l = "serifed-flat-tailed"
		m = "earless-rounded-double-arch-short-leg-serifless"
		n = "earless-rounded-straight-serifless"
		p = "earless-rounded-serifless"
		q = "earless-rounded-straight-serifless"
		r = "earless-rounded-serifless"
		t = "flat-hook-asymmetric-short-neck"
		u = "toothless-rounded-serifless"
		v = "curly-serifless"
		w = "cursive-serifless"
		y = "cursive-flat-hook-serifless"
		asterisk = "hex-mid"
		underscore = "high"
		paren = "large-contour"
		brace = "curly-flat-boundary"
		ampersand = "upper-open"
		at = "compact"
		dollar = "interrupted"
		cent = "open"
		bar = "natural-slope"
		question = "smooth"
		pilcrow = "high"
		lig-ltgteq = "slanted"
		lig-neq = "slightly-slanted"
		lig-equal-chain = "without-notch"
		lig-hyphen-chain = "without-notch"

	[buildPlans.IosevkaFelix.ligations]
	inherits = "dlig"